### ISSUE TITLE
Scratch Pad management

### ISSUE THREAD

**Issue by dominique09** [ronyan/VATCANSitu#20]
Label as enhencement

Manage Scratch pad to ignore leading space (leading space enter manually to avoid write a FIX name)
Is this logic could be good ? ==> If the first 2 chars are 1 or 2 chars followed by a space it stay in SFI, and the rest go down in Controllers Notes. If longer than 2 chars go directly in Controllers notes.

**Comment by ronyan** [comment]
I think I have it working as you described. Should account for edge cases where you want to put something like "NEW PILOT" (with spaces) into the remarks. Let me know!
