### ISSUE TITLE
PTL seems to not follow the good HDG when scope is set as True North

### ISSUE THREAD

**Issue by dominique09** [ronyan/VATCANSitu#21]
True North
![image](https://user-images.githubusercontent.com/8714449/101316265-2e35ed00-382a-11eb-9fda-bb191d6916da.png)
Magnetic North
![image](https://user-images.githubusercontent.com/8714449/101316298-3d1c9f80-382a-11eb-9071-0650ab75298d.png)

**Comment by ronyan** [comment]
Fixed this in c1e4044

Will pull into main branch soon!

**Comment by ronyan** [comment]
c1e4044

merged
