### ISSUE TITLE
Trouble with the menu

### ISSUE THREAD

**Issue by dominique09** [ronyan/VATCANSitu#36]
Trouble with the menu
https://gyazo.com/63229de461cf5d7c07615f7bcebc31e5

**Comment by dominique09** [comment]
![image](https://user-images.githubusercontent.com/8714449/106339546-ebf6be00-6264-11eb-9bb4-de7650f23241.png)

**Comment by ronyan** [comment]
pushing some builds in the middle of refactoring after getting some new pictures from the real scope! fixed now in ff2cdb1

![image](https://user-images.githubusercontent.com/2171625/106359696-9ebd2f80-62ea-11eb-9804-71bc7e7dd321.png)
