### ISSUE TITLE
Passing build plugin error

### ISSUE THREAD

**Issue by occidiovivo** [ronyan/VATCANSitu#55]
Loading the VATCANSitu passing build from 1.0.130 and higher is throwing a ES load plugin error:  Unhandled exception in plug-in: VATACANSitu 

https://prnt.sc/1raweod

**Comment by natopower** [comment]
Similar to this - re-creatable when opening the .PRF from outside of the main folder (eg. opening from a shortcut instead of from directly inside ".../Euroscope".

**Comment by Mistadouf** [comment]
Have you tried deleting the settings.json file in situWx folder and let the plugin rebuild a new one?

**Comment by occidiovivo** [comment]
Thank you, that did indeed work.
