### ISSUE TITLE
After long session (3h) scope starts to freeze

### ISSUE THREAD

**Issue by dominique09** [ronyan/VATCANSitu#60]
I don't know if it's related to Situ or not but after a 3h use, euroscope start de freeze while writing text and trying to change items in lists.

**Comment by ronyan** [comment]
https://ci.appveyor.com/project/ronyan/vatcansitu

did you try the latest build where I'm trying to incoporate some of Liam's enhancements? the new one has some garbage cleaning for the data stored by the plugin, should keep the long sessions a bit more manageable

**Comment by dominique09** [comment]
Just did it. It work fine now ! Thx
